repos:
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
        language_version: python3.7
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
      - id: flake8
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v5.16.0 # Use the sha / tag you want to point at
    hooks:
      - id: eslint
        additional_dependencies:
        - eslint@5.16.0
        - eslint-config-react-app@4.0.1
        - eslint-import-resolver-node@0.3.2
        - eslint-loader@2.1.2
        - eslint-module-utils@2.4.0
        - eslint-plugin-flowtype@2.50.1
        - eslint-plugin-import@2.16.0
        - eslint-plugin-jsx-a11y@6.2.1
        - eslint-plugin-react@7.12.4
        - eslint-plugin-react-hooks@1.6.0
        - eslint-scope@4.0.3
        - eslint-utils@1.3.1
        - eslint-visitor-keys@1.0.0
        - babel-eslint@10.0.1
