version: "3.7"

services:
  maps:
    # served as a static file with https://hub.docker.com/_/nginx/
    build:
      context: services/maps/
      dockerfile: Dockerfile
    image: ghcr.io/diegoquintanav/pinochet-analyze/pinochet-maps:latest
    restart: always
    ports:
      - 80:80
    networks:
      - maps_nw

networks:
  maps_nw:
    driver: bridge
