version: "3.7"

services:
  core1:
    image: neo4j:3.5-enterprise
    # image: neo4j:4.0.1-enterprise
    networks:
      - neo4j_nw
    ports:
      - 7474:7474
      - 6477:6477
      - 7687:7687
    volumes:
      - $HOME/neo4j/neo4j-core1/conf:/conf
      - $HOME/neo4j/neo4j-core1/data:/data
      - $HOME/neo4j/neo4j-core1/logs:/logs
      - $HOME/neo4j/neo4j-core1/plugins:/plugins
      - $HOME/neo4j/neo4j-core1/import:/import
    environment:
      - NEO4J_AUTH=none
      # - NEO4J_AUTH=neo4j/admin
      # - NEO4J_dbms_mode=CORE
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      # - NEO4J_dbms_default__database=dblp.db # 4.0.1-enterprise
      # - NEO4J_dbms_active__database=dblp_slim.db # 3.5-enterprise
      - NEO4J_dbms_active__database=pinochet.db # 3.5-enterprise
      - NEO4J_dbms_connector_http_listen__address=:7474
      - NEO4J_dbms_connector_https_listen__address=:6477
      - NEO4J_dbms_connector_bolt_listen__address=:7687
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,algo.*
      - NEO4J_apoc_import_file_enabled=true
  maps:
    # served as a static file with https://hub.docker.com/_/nginx/
    build:
      context: services/maps/
      dockerfile: Dockerfile-dev
    image: pinochet-maps:development
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./services/maps/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - maps_nw

networks:
  maps_nw:
    driver: bridge
  neo4j_nw:
    driver: bridge
